version = 1

[[analyzers]]
name = "kube-linter"
type = "community"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = [
    "src/api-gateway/Dockerfile",
    "src/user-service/Dockerfile",
    "src/post-service/Dockerfile",
    "src/notification-service/Dockerfile",
    "src/mail-service/Dockerfile"
  ]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/wwi21seb-projekt/alpha-services"
  import_paths = [
    "github.com/wwi21seb-projekt/alpha-services/src/api-gateway", 
    "github.com/wwi21seb-projekt/alpha-services/src/user-service", 
    "github.com/wwi21seb-projekt/alpha-services/src/post-service", 
    "github.com/wwi21seb-projekt/alpha-services/src/notification-service", 
    "github.com/wwi21seb-projekt/alpha-services/src/mail-service"
  ]