apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: serveralpha
build:
  artifacts:
    - image: api-gateway-image
      context: src/api-gateway
      docker:
        dockerfile: Dockerfile
    - image: chat-service-image
      context: src/chat-service
      docker:
        dockerfile: Dockerfile
    - image: post-service-image
      context: src/post-service
      docker:
        dockerfile: Dockerfile
    - image: user-service-image
      context: src/user-service
      docker:
        dockerfile: Dockerfile
    - image: mail-service-image
      context: src/mail-service
      docker:
        dockerfile: Dockerfile
    - image: notification-service-image
      context: src/notification-service
      docker:
        dockerfile: Dockerfile   
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
    concurrency: 4
manifests:
  kustomize:
    paths:
      - k8s/base
portForward:
  - resourceType: service
    resourceName: api-gateway
    namespace: default
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: postgres
    namespace: default
    port: 5432
    localPort: 5432
profiles:
  - name: local
    activation:
      - command: dev
    manifests:
      kustomize:
        paths:
          - k8s/overlays/local
  - name: prod
    activation:
      - command: run
    manifests:
      kustomize:
        paths:
          - k8s/overlays/prod
