apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: serveralpha
build:
  artifacts:
    - image: api-gateway-image
      context: src/api-gateway
      docker:
        dockerfile: Dockerfile
    - image: post-service-image
      context: src/post-service
      docker:
        dockerfile: Dockerfile
    - image: user-service-image
      context: src/user-service
      docker:
          dockerfile: Dockerfile
  local:
    useBuildkit: true
    concurrency: 4
manifests:
  kustomize:
    paths:
      - k8s/base
portForward:
  - resourceType: service
    resourceName: api-gateway
    namespace: default
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: postgres
    namespace: default
    port: 5432
    localPort: 5432
