apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  mode: daemonset
  config:
    exporters:
      otlp/jaeger:
        endpoint: "jaegertracing-collector.observability:4317"