apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          image: api-gateway-image:latest

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  template:
    spec:
      containers:
        - name: post-service
          image: post-service-image:latest
