apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  # collector:
  #   maxReplicas: 1
  #   resources:
  #     limits:
  #       cpu: 100m
  #       memory: 128Mi
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jaeger-operator-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: jaeger-operator
    namespace: default
roleRef:
  kind: Role
  name: jaeger-operator
  apiGroup: rbac.authorization.k8s.io
