apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              value: "local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  template:
    spec:
      containers:
        - name: chat-service
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              value: "local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  template:
    spec:
      containers:
        - name: user-service
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              value: "local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  template:
    spec:
      containers:
        - name: post-service
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              value: "local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  template:
    spec:
      containers:
        - name: mail-service
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              value: "local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  template:
    spec:
      containers:
        - name: notification-service
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              value: "local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
spec:
  template:
    spec:
      containers:
        - name: image-service
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              value: "local"
