apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  template:
    spec:
      containers:
        - name: chat-service
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  template:
    spec:
      containers:
        - name: user-service
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  template:
    spec:
      containers:
        - name: post-service
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  template:
    spec:
      containers:
        - name: mail-service
          imagePullPolicy: Never
