apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-scripts
data:
  init.sql: |
    {{- .Files.Get "files/init-script.sql" | nindent 4}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  ENVIRONMENT: "{{ .Values.overrideConfigMap.ENVIRONMENT | default "development" }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ default (printf "http://%s-opentelemetry-collector:4317" .Release.Name) .Values.overrideConfigMap.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
  POSTGRES_HOST: "{{ default (printf "%s-postgresql" .Release.Name) .Values.overrideConfigMap.POSTGRES_HOST }}"
  POSTGRES_PORT: "{{ default "5432" .Values.overrideConfigMap.POSTGRES_PORT }}"
  POSTGRES_DB: {{ default .Values.postgresql.auth.database .Values.overrideConfigMap.POSTGRES_DB | quote }}

