apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-image-store
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
      - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/image-service
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-image-store-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  storageClassName: standard
  accessModes:
      - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi