apiVersion: v1
kind: Secret
metadata:
  name: alpaca-secrets
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  POSTGRES_NAME: {{ .Values.secret.postgresName | b64enc | quote }}
  POSTGRES_USER: {{ .Values.secret.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | b64enc | quote }}
  DATABASE_URL: {{ .Values.secret.databaseUrl | b64enc | quote }}
  JWT_PRIVATE_KEY: {{ .Values.secret.jwtPrivateKey | quote }}
  JWT_PUBLIC_KEY: {{ .Values.secret.jwtPublicKey | quote }}
  MAILGUN_API_KEY: {{ .Values.secret.mailgunApiKey | b64enc | quote }}
  VAPID_PUBLIC_KEY: {{ .Values.secret.vapidPublicKey | quote }}
  VAPID_PRIVATE_KEY: {{ .Values.secret.vapidPrivateKey | quote }}
