apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secretOverride.POSTGRES_USER | default .Values.postgresql.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secretOverride.POSTGRES_PASSWORD | default .Values.postgresql.auth.password | b64enc | quote }}
  JWT_PRIVATE_KEY: {{ .Values.secretOverride.JWT_PRIVATE_KEY_BASE64 | default ( .Files.Get "files/private.ed25519.key" | b64enc ) | quote }}
  JWT_PUBLIC_KEY: {{ .Values.secretOverride.JWT_PUBLIC_KEY_BASE64 | default ( .Files.Get "files/public.ed25519.key" | b64enc ) | quote }}
  MAILGUN_API_KEY: {{ .Values.secretOverride.MAILGUN_API_KEY | b64enc | quote }}
  VAPID_PUBLIC_KEY: {{ .Values.secretOverride.VAPID_PUBLIC_KEY | default ( .Files.Get "files/vapid-public.key" ) | b64enc | quote }}
  VAPID_PRIVATE_KEY: {{ .Values.secretOverride.VAPID_PRIVATE_KEY | default ( .Files.Get "files/vapid-private.key" ) | b64enc | quote }}
