apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: chat-service-image
          ports:
            - containerPort: 50055
          env:
            - name: PORT
              value: "50055"
            - name: USER_SERVICE_URL
              value: "user-service:50052"
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: SCHEMA_NAME
              value: chat_service
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: alpha-secrets
                  key: POSTGRES_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: alpha-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alpha-secrets
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 50055
      targetPort: 50055
