apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
        - name: image-service
          image: image-service-image
          imagePullPolicy: Always
          resources:
            limits:
              memory: 100Mi
          ports:
            - containerPort: 50056
          env:
            - name: PORT
              value: "50056"
            - name: ENVIRONMENT
              value: "production"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
          volumeMounts:
            - name: image-service-storage
              mountPath: /serveralpha/data
      volumes:
        - name: image-service-storage
          persistentVolumeClaim:
            claimName: image-service-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: image-service
  labels:
    app: image-service
spec:
  selector:
    app: image-service
  ports:
    - protocol: TCP
      name: grpc
      port: 50056
      targetPort: 50056

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-service-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/image-service
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-service-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
