apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  collector:
    maxReplicas: 1
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
