resources:
  - api-gateway.yaml
  - chat-service.yaml
  - post-service.yaml
  - user-service.yaml
  - mail-service.yaml
  - postgres.yaml
  - otel-config.yaml
  - notification-service.yaml
  - image-service.yaml
