apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
        - name: mail-service
          image: mail-service-image
          imagePullPolicy: Always
          resources:
            limits:
              memory: 100Mi
          ports:
            - containerPort: 50053
            - containerPort: 2112
          env:
            - name: PORT
              value: "50053"
            - name: ENVIRONMENT
              value: "production"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: alpha-secrets
                  key: MAILGUN_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
  labels:
    app: mail-service
spec:
  selector:
    app: mail-service
  ports:
    - protocol: TCP
      name: grpc
      port: 50053
      targetPort: 50053
    # metrics server
    - protocol: TCP
      name: metrics
      port: 2112
      targetPort: 2112
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mail-service
  labels:
    team: team-alpha
    release: alpha-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: mail-service
  endpoints:
    - port: metrics
      path: /metrics
