apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: post-service-image
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: USER_ADDR
              value: "user-service:50052"
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051