name: Atlas
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci-atlas.yaml
      - "db/migrations/*"
  pull_request:
    paths:
      - "db/migrations/*"
# Permissions to write comments on the pull request.
permissions:
  contents: read
  pull-requests: write
jobs:
  atlas:
    services:
      # Spin up a postgres:16 container to be used as the dev-database for analysis.
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: dev
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN }}
      - uses: ariga/atlas-action/migrate/lint@v1
        with:
          dir: "file://db/migrations"
          dev-url: "postgres://postgres:pass@localhost:5432/dev?sslmode=disable"
          dir-name: "alpha-db"
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: ariga/atlas-action/migrate/push@v1
        if: github.ref == 'refs/heads/main'
        with:
          dir: "file://db/migrations"
          dev-url: "postgres://postgres:pass@localhost:5432/dev?sslmode=disable"
          dir-name: "alpha-db"
