name: Check Kubernetes Configuration
run-name: Check Kubernetes Configuration for ${{ github.event_name == 'pull_request' && format('PR-{0}', github.event.number) || 'main' }}

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

env:
  DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

jobs:
  check-k8s:
    name: Check Kubernetes Configuration
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Scan repo with kube-linter
        uses: stackrox/kube-linter-action@v1.0.5
        with:
          directory: k8s
          format: sarif
          output-file: kube-linter.sarif
        ## Since the kube-linter-action fails, we need to add a workaround to continue the workflow
        continue-on-error: true

      - name: Upload kube-linter SARIF
        run: |
          # Install the DeepSource CLI
            curl https://deepsource.io/cli | sh

            # Upload the kube-linter SARIF file to DeepSource
            ./bin/deepsource report --analyzer kube-linter --analyzer-type community --value-file ./kube-linter.sarif
