name: Continuous Integration
run-name: CI Checks [PR-${{ github.event.pull_request.number }}]

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, post-service, user-service, mail-service]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: Determine if the service has changed
        id: changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^src/${{ matrix.service }}/"; then
            echo "service_changed=true" >> $GITHUB_ENV
          else
            echo "service_changed=false" >> $GITHUB_ENV
          fi

      - name: Install Staticcheck
        if: env.service_changed == 'true'
        run: |
          cd src/${{ matrix.service }}
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Build project and verify dependencies
        if: env.service_changed == 'true'
        run: |
          cd src/${{ matrix.service }}
          go build -v ./... && go mod verify

      - name: Verify Code Quality
        if: env.service_changed == 'true'
        run: |
          cd src/${{ matrix.service }}
          go vet ./... && staticcheck ./...

      - name: Run Tests
        if: env.service_changed == 'true'
        run: |
          cd src/${{ matrix.service }}
          go test ./...
