name: Continuous Integration
run-name: CI Checks [PR-${{ github.event.pull_request.number }}]

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, post-service, user-service, mail-service]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            ${{ matrix.service }}:
              - 'src/${{ matrix.service }}/**'

      - name: Set up Go
        if: ${{ steps.filter.outputs[ matrix.service ] == 'true' }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'
          check-latest: true
          cache-dependency-path: "src/${{ matrix.service }}/go.sum"

      - name: Install Staticcheck
        if: ${{ steps.filter.outputs[ matrix.service ] == 'true' }}
        run: |
          cd src/${{ matrix.service }}
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Build project and verify dependencies
        if: ${{ steps.filter.outputs[ matrix.service ] == 'true' }}
        run: |
          cd src/${{ matrix.service }}
          go build -v ./... && go mod verify

      - name: Verify Code Quality
        if: ${{ steps.filter.outputs[ matrix.service ] == 'true' }}
        run: |
          cd src/${{ matrix.service }}
          go vet ./... && staticcheck ./...

      - name: Run Tests
        if: ${{ steps.filter.outputs[ matrix.service ] == 'true' }}
        run: |
          cd src/${{ matrix.service }}
          go test -v ./...
